project_id = "gnxrpoviakaqdanaxlfn"

[functions.ai-generate]
verify_jwt = false

[functions.ai-generate-openai]
verify_jwt = false

[functions.analyze-ads]
verify_jwt = false

[functions.business-advisor]
verify_jwt = false

[functions.design-ad]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.product-photo-prompt]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.search-facebook-ads]
verify_jwt = false

[functions.nzmly-webhook]
verify_jwt = false
